debug = true
app_secret = "change it"
host = "0.0.0.0"
port = 3180
version = "0.0.1"
server_name = "rufu"
database_url = ""
jwt_secret = "rufu_jwt_secret"
jwt_expire = 60
swagger_url = "/swagger-ui"
openapi_url = "/api-docs/openapi.json"
super_admin_id = ""
role_domain = "ADMIN,API"