[package]
name = "rufu_permission"
version = "0.1.0"
edition = "2021"
authors = [
    "ifui <ifui@foxmail.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
rbatis = "4.5"